using UnityEngine;
using UnityEngine.SceneManagement;
using System.Collections;

public class MonitorTapHotspot : MonoBehaviour
{
    [Header("Scene")]
    [SerializeField] private string mazeSceneName = "Game01";

    [Header("This monitor's index (0 or 1)")]
    [SerializeField] private int hackedIndex = 0;

    [Header("Intro & Loading Animation")]
    [SerializeField] private Canvas logoIntroCanvas;
    [SerializeField] private CanvasGroup logoCanvasGroup;
    [SerializeField] private Canvas loadingCanvas;
    [SerializeField] private CanvasGroup loadingCanvasGroup;
    
    [Header("Timing")]
    [SerializeField] private float fadeDuration = 0.15f;
    [SerializeField] private float logoDuration = 1f;

    [Header("Player")]
    [SerializeField] private Transform playerTransform;

    [Header("UI to hide on tap")]
    [SerializeField] private GameObject[] uiElementsToHide;

    private bool busy;
    private float sceneStartTime;

    private void Awake()
    {
        sceneStartTime = Time.time;

        // Hide overlay canvases at start
        SetupOverlay(logoIntroCanvas, logoCanvasGroup, false, 0f);
        SetupOverlay(loadingCanvas, loadingCanvasGroup, false, 0f);
    }

    public void OnTapped()
    {
        // 1. Safety Lock: Ignore clicks for the first 1 second of this scene loading
        // (Prevents phantom UI clicks generated by Unity at startup)
        if (Time.time - sceneStartTime < 1.0f)
        {
            Debug.LogWarning("[MonitorTapHotspot] Ignored phantom tap at scene start.");
            return;
        }

        if (busy) return;

        if (hackedIndex < 0 || hackedIndex > 1)
        {
            Debug.LogWarning($"[MonitorTapHotspot] Invalid hackedIndex={hackedIndex}. Use 0 or 1.");
            return;
        }

        busy = true;

        HackedRunState.SetLastHackedIndex(hackedIndex);
        Debug.Log($"MonitorTapHotspot: tapped hacked index {hackedIndex}", this);

        if (uiElementsToHide != null)
        {
            foreach (var go in uiElementsToHide)
                if (go) go.SetActive(false);
        }

        // Start transition ONLY after tapped
        StartCoroutine(LoadMazeRoutine());
    }

    public void OnTappedWithIndex(int index)
    {
        hackedIndex = index;
        OnTapped();
    }

    private IEnumerator LoadMazeRoutine()
    {
        // 1. Show the Loading Screen and Logo immediately
        SetupOverlay(logoIntroCanvas, logoCanvasGroup, true, 0f);
        SetupOverlay(loadingCanvas, loadingCanvasGroup, true, 0f);

        if (logoCanvasGroup)
            StartCoroutine(FadeCanvasGroup(logoCanvasGroup, 0f, 1f, fadeDuration));

        if (loadingCanvasGroup)
            StartCoroutine(FadeCanvasGroup(loadingCanvasGroup, 0f, 1f, fadeDuration));

        // 2. Wait for the fade animation to finish
        if (fadeDuration > 0f)
            yield return new WaitForSecondsRealtime(fadeDuration);

        // 3. Save player pose
        if (playerTransform) 
            LabReturnState.SavePlayerPose(playerTransform);

        // Wait to meet the minimum logo duration
        float waitBeforeLoad = Mathf.Max(0f, logoDuration - fadeDuration);
        if (waitBeforeLoad > 0f)
            yield return new WaitForSecondsRealtime(waitBeforeLoad);

        // 4. NOW load the scene (No background preloads that cause bugs!)
        AsyncOperation op = SceneManager.LoadSceneAsync(mazeSceneName);

        // Wait for Unity to completely finish the scene switch
        while (op != null && !op.isDone)
            yield return null;
    }

    private IEnumerator FadeCanvasGroup(CanvasGroup cg, float from, float to, float duration)
    {
        float t = 0f;
        cg.alpha = from;
        while (t < duration)
        {
            t += Time.unscaledDeltaTime;
            cg.alpha = Mathf.Lerp(from, to, t / duration);
            yield return null;
        }
        cg.alpha = to;
    }

    private void SetupOverlay(Canvas canvas, CanvasGroup canvasGroup, bool enabled, float alpha)
    {
        if (canvas)
            canvas.enabled = enabled;

        if (canvasGroup)
        {
            canvasGroup.alpha = alpha;
            canvasGroup.blocksRaycasts = enabled;
            canvasGroup.interactable = enabled;
        }
    }
}